version: '3.8'

services:
  frontend:
    build: ./expensy_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3100
    depends_on:
      - backend

  backend:
    build: ./expensy_backend
    ports:
      - "3100:3100"
    environment:
      - DATABASE_URI=mongodb://mongo:27017/expensy
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=someredispassword
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "someredispassword"]

networks:
  default:
    driver: bridge