# Use an official Node.js runtime as a parent image
FROM node:18-alpine
 
# Set the working directory in the container
WORKDIR /app
 
# Copy package.json and package-lock.json
COPY package*.json ./
 
# Install dependencies
RUN npm install
 
# Copy the rest of the application code
COPY . .
 
RUN npm run build
 
# Expose the port the app runs on
EXPOSE 3100
 
# Command to run the application
CMD ["node", "./dist/server.js"]