apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: kbaigorri/kbaigorri-proyectofinal:backtag
        ports:
        - containerPort: 3100
        env:
        - name: DATABASE_URI
          value: "mongodb://mongo-service:27017"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: "someredispassword"
        - name: PORT
          value: "3100"       
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
  type: ClusterIP